version: '3'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_ROOT_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    expose: 
      - ${MYSQL_LOCAL_PORT}
    # networks:
    #   - app-network
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: node-mysql-app
  #   depends_on:
  #     - mysqldb
  #   stdin_open: true
    # tty: true
    # networks:
    #   - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes: 
#   db-data: {}
